version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent-wireguard_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

server:
  image: tenseiken/qbittorrent-wireguard:latest
  ports:
    - “8080:8080“
  environment:
    - ENABLEPROTONVPNPORTFWD=1
    - LAN_NETWORK=192.168.1.0/24
    - PGID=1000
    - PUID=1000
    - QBT_LEGAL_NOTICE=confirm
    - WEBUI_PASS=adminadmin
    - WEBUI_URL=8080
    - WEBUI_USER=admin
    # - UMASK=002
  volumes:
    - ${APP_DATA_DIR}/data/config:/config
    # /app/qBittorrent/downloads is the default path set in qBittorrent
    - ${UMBREL_ROOT}/data/storage/downloads:/app/qBittorrent/downloads
  cap_add:
    - NET_ADMIN
  sysctls:
    - net.ipv4.conf.all.rp_filter=2
    - net.ipv4.conf.all.src_valid_mark=1
  restart: always
